//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3649
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTATools.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTATools.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Can not get update file info 的本地化字符串。
        /// </summary>
        public static string cannotGetUpdateFileInfo {
            get {
                return ResourceManager.GetString("cannotGetUpdateFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not upload 的本地化字符串。
        /// </summary>
        public static string cannotUpload {
            get {
                return ResourceManager.GetString("cannotUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Modification record] 的本地化字符串。
        /// </summary>
        public static string changeLog {
            get {
                return ResourceManager.GetString("changeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client name:{0} 的本地化字符串。
        /// </summary>
        public static string clientName {
            get {
                return ResourceManager.GetString("clientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Committing data... 的本地化字符串。
        /// </summary>
        public static string committing {
            get {
                return ResourceManager.GetString("committing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create time:{0} 的本地化字符串。
        /// </summary>
        public static string createTime {
            get {
                return ResourceManager.GetString("createTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm delete 的本地化字符串。
        /// </summary>
        public static string deleteConfirm {
            get {
                return ResourceManager.GetString("deleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete this device? 的本地化字符串。
        /// </summary>
        public static string deleteDevice {
            get {
                return ResourceManager.GetString("deleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete fail 的本地化字符串。
        /// </summary>
        public static string deleteFail {
            get {
                return ResourceManager.GetString("deleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete success 的本地化字符串。
        /// </summary>
        public static string deleteSuccess {
            get {
                return ResourceManager.GetString("deleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete this update file? 的本地化字符串。
        /// </summary>
        public static string deleteUpdateFile {
            get {
                return ResourceManager.GetString("deleteUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting file... 的本地化字符串。
        /// </summary>
        public static string deleting {
            get {
                return ResourceManager.GetString("deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description:{0} 的本地化字符串。
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device id:{0} 的本地化字符串。
        /// </summary>
        public static string deviceId {
            get {
                return ResourceManager.GetString("deviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Device info] 的本地化字符串。
        /// </summary>
        public static string deviceInfo {
            get {
                return ResourceManager.GetString("deviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device model:{0} 的本地化字符串。
        /// </summary>
        public static string deviceModel {
            get {
                return ResourceManager.GetString("deviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CFG file|*.cfg 的本地化字符串。
        /// </summary>
        public static string fileFilter {
            get {
                return ResourceManager.GetString("fileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name:{0} 的本地化字符串。
        /// </summary>
        public static string fileName {
            get {
                return ResourceManager.GetString("fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not exist 的本地化字符串。
        /// </summary>
        public static string fileNotExist {
            get {
                return ResourceManager.GetString("fileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File size{0} 的本地化字符串。
        /// </summary>
        public static string fileSize {
            get {
                return ResourceManager.GetString("fileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not get file md5 的本地化字符串。
        /// </summary>
        public static string getMd5Fial {
            get {
                return ResourceManager.GetString("getMd5Fial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting device list 的本地化字符串。
        /// </summary>
        public static string getting_devices {
            get {
                return ResourceManager.GetString("getting_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting device list... 的本地化字符串。
        /// </summary>
        public static string gettingDeviceList {
            get {
                return ResourceManager.GetString("gettingDeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting file info... 的本地化字符串。
        /// </summary>
        public static string gettingFileInfo {
            get {
                return ResourceManager.GetString("gettingFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting update file info... 的本地化字符串。
        /// </summary>
        public static string gettingUpdateFileInfo {
            get {
                return ResourceManager.GetString("gettingUpdateFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid ID 的本地化字符串。
        /// </summary>
        public static string invalidID {
            get {
                return ResourceManager.GetString("invalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading list... 的本地化字符串。
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging.. 的本地化字符串。
        /// </summary>
        public static string logging {
            get {
                return ResourceManager.GetString("logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login fail 的本地化字符串。
        /// </summary>
        public static string loginFail {
            get {
                return ResourceManager.GetString("loginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MD5：{0} 的本地化字符串。
        /// </summary>
        public static string md5 {
            get {
                return ResourceManager.GetString("md5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device model existing 的本地化字符串。
        /// </summary>
        public static string modelExisting {
            get {
                return ResourceManager.GetString("modelExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters cannot be empty 的本地化字符串。
        /// </summary>
        public static string Parameterscannotempty {
            get {
                return ResourceManager.GetString("Parameterscannotempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release time:{0} 的本地化字符串。
        /// </summary>
        public static string releaseTime {
            get {
                return ResourceManager.GetString("releaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving device list... 的本地化字符串。
        /// </summary>
        public static string savingDeviceList {
            get {
                return ResourceManager.GetString("savingDeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving update list... 的本地化字符串。
        /// </summary>
        public static string savingUpdateList {
            get {
                return ResourceManager.GetString("savingUpdateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary:{0} 的本地化字符串。
        /// </summary>
        public static string summaryInfo {
            get {
                return ResourceManager.GetString("summaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update file already exist in server 的本地化字符串。
        /// </summary>
        public static string updateFileExist {
            get {
                return ResourceManager.GetString("updateFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Update file)|*.zip 的本地化字符串。
        /// </summary>
        public static string updateFileFilter {
            get {
                return ResourceManager.GetString("updateFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update file if:{0} 的本地化字符串。
        /// </summary>
        public static string updateFileId {
            get {
                return ResourceManager.GetString("updateFileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Update file info] 的本地化字符串。
        /// </summary>
        public static string updateFileInfo {
            get {
                return ResourceManager.GetString("updateFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload speed:{0}KB/S,finished {1}%,remaining {2} minute(s) 的本地化字符串。
        /// </summary>
        public static string uploadSpeed {
            get {
                return ResourceManager.GetString("uploadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version:{0} 的本地化字符串。
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The version is invalid 的本地化字符串。
        /// </summary>
        public static string versionInvalid {
            get {
                return ResourceManager.GetString("versionInvalid", resourceCulture);
            }
        }
    }
}
